# Generated by Django 3.0.3 on 2020-12-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_org', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='users',
            new_name='members',
        ),
    ]
